"""Apply original revision content to the existing canonical Biology catalog.

Reference boundaries independently checked in IB's Biology guide (2025 first
assessment), printed pp. 67-71. This does not reproduce the guide's prose,
figures or questions. Numerical datasets below are synthetic practice data.
Existing resource keys are retained so saved review history is not replaced.
"""
import json
from pathlib import Path

path = Path('IBVault/Materials/Biology/C.json')
topics = json.loads(path.read_text())
by_code = {topic['code']: topic for topic in topics}


def section(code, key, title, points, body, pitfall, hl=False):
    return dict(key=key, title=title, syllabusPoints=[f'{code}.{i}' for i in points],
                body=body, pitfall=pitfall, hlOnly=hl)


def question(key, section_key, kind, command, prompt, answer, explanation,
             distractors=(), hl=False):
    return dict(key=key, sectionKey=section_key, kind=kind, command=command,
                prompt=prompt, answer=answer, distractors=list(distractors),
                explanation=explanation, hlOnly=hl)


r = by_code['C1.2']
old_r = {q['key']: q for q in r['questions']}
r['sections'] = [
    section('C1.2', 'atp', 'ATP as a shared energy carrier', [1, 2],
        'ATP (adenosine triphosphate) is a nucleotide containing adenine, ribose and three phosphate groups. Cells use ATP as an immediately available energy carrier, not as their main long-term energy reserve. Both autotrophs and heterotrophs use it.\n\nATP-dependent reactions support active transport against concentration gradients, synthesis of larger molecules from smaller ones, and movement such as muscle contraction or movement along a cytoskeleton. Enzymes couple ATP use to these processes rather than releasing energy at an unrelated location. Plants continue to require ATP for cellular work in darkness as well as in light.',
        'ATP is neither an enzyme nor a store of energy that is used only by animals.'),
    section('C1.2', 'atp-cycle', 'ATP use and regeneration', [3],
        'ATP + water → ADP + inorganic phosphate is an energy-releasing hydrolysis overall. The reverse conversion, ADP + phosphate → ATP, requires an energy input. Respiration supplies energy for much of this regeneration; photosynthesis also produces ATP within chloroplasts.\n\nATP and ADP are continually recycled. A small ATP pool can support extensive cellular work because its molecules are regenerated repeatedly. An ATP concentration that remains steady therefore does not imply that ATP is unused. If ATP production stops while ATP-dependent work continues, the ATP pool falls.\n\nBond breaking itself requires energy. ATP hydrolysis releases energy overall because the complete reaction, including formation and stabilization of products, is energetically favourable.',
        'Do not explain ATP hydrolysis as energy being released simply by breaking a bond.'),
    section('C1.2', 'pathways', 'Respiration in human cells', [4, 5],
        'Cell respiration is a sequence of enzyme-controlled reactions transferring energy from carbon compounds into ATP and heat. It is not the same process as ventilation or exchange of oxygen and carbon dioxide. Glucose and, in aerobic pathways, fatty acids can be respiratory substrates.\n\nA simplified aerobic equation is C6H12O6 + 6 O2 → 6 CO2 + 6 H2O. In human cells, glucose breakdown starts in the cytoplasm and aerobic stages continue in mitochondria. Aerobic respiration has a much larger ATP yield per glucose than the anaerobic route.\n\nHuman cells can obtain a small amount of ATP by converting glucose to lactate without using oxygen. This occurs in the cytoplasm, helps working muscles when demand exceeds oxygen supply, and supplies mature red blood cells, which have no mitochondria. Lactate formation does not release carbon dioxide.',
        'Aerobic and anaerobic pathways are not simply switched on and off throughout the whole body together.'),
    section('C1.2', 'respirometry', 'Measuring a respiration rate', [6],
        'A respirometer can estimate oxygen uptake from a change in gas volume. An absorbent removes carbon dioxide so that its release does not offset oxygen uptake. Keep the absorbent separate from living tissue. Check seals and allow temperature and pressure to equilibrate before measuring.\n\nRate = change in oxygen volume / elapsed time. Divide by tissue mass when comparing unequal samples. For example, uptake of 0.48 cm³ in 4 minutes by 2.0 g of seeds is 0.060 cm³ g⁻¹ min⁻¹. With a capillary, volume change equals movement distance multiplied by its cross-sectional area.\n\nAn identical apparatus containing inert beads or killed tissue helps detect physical changes unrelated to living respiration. Match occupied volume, hold temperature and other conditions constant, use independent replicates, and report variation. Oxygen uptake alone does not measure anaerobic ATP production.',
        'Gas contraction is not automatically oxygen uptake if carbon dioxide, leaks or temperature changes are uncontrolled.'),
    section('C1.2', 'redox', 'Hydrogen and electron carriers', [7],
        'Oxidation is loss of electrons; reduction is gain of electrons. During respiration, removal of hydrogen from a carbon compound is an oxidation, and a carrier accepts the electrons. NAD+ is the oxidized form of a carrier. NAD+ + 2 electrons + H+ → NADH represents its reduction; another hydrogen ion may be released into the surrounding solution during substrate oxidation.\n\nNADH carries reducing power to another reaction and is oxidized back to NAD+. These are forms of the same recyclable carrier, not different energy sources created from nothing. Continued oxidation of substrate requires a supply of the oxidized carrier. NADH is not ATP and does not directly substitute for ATP in most ATP-dependent work.',
        'Reduced NAD means NAD has gained electrons, not that its quantity has decreased.', True),
    section('C1.2', 'glycolysis', 'Following glucose through glycolysis', [8],
        'Glycolysis occurs in the cytoplasm. A six-carbon glucose molecule is phosphorylated using two ATP, then split into two three-carbon intermediates. Their oxidation reduces NAD+ to NADH. Subsequent reactions transfer phosphate directly from intermediates to ADP, producing four ATP by substrate-level phosphorylation.\n\nPer glucose, the net result is two pyruvate, two NADH and two ATP: four ATP are made but two were invested. The six carbon atoms remain in the two three-carbon pyruvate molecules, so glycolysis releases no carbon dioxide. It does not use oxygen directly, but it can continue only if NAD+ is regenerated from NADH.',
        'Four ATP formed is the gross output, not the net ATP yield of glycolysis.', True),
    section('C1.2', 'fermentation', 'Keeping glycolysis supplied with NAD+', [9, 10],
        'When pyruvate is reduced to lactate in human cells, NADH is oxidized to NAD+. This regenerates the carrier required by glycolysis. The conversion to lactate adds no extra ATP; the net yield remains two ATP per glucose from glycolysis.\n\nIn yeast, pyruvate loses carbon dioxide and the remaining two-carbon compound is reduced to ethanol, regenerating NAD+. Ethanol and carbon dioxide are useful products in brewing and bread making: carbon dioxide expands dough, while ethanol is the desired product in alcoholic fermentation.\n\nThe human lactate pathway and yeast ethanol pathway therefore differ in carbon products, although both maintain glycolytic ATP production without oxygen. If the NAD+ pool is exhausted, glycolysis cannot sustain ATP production merely because glucose remains.',
        'Human lactate formation does not generate the carbon dioxide produced in the yeast pathway.', True),
    section('C1.2', 'link', 'From pyruvate to acetyl-CoA', [11],
        'In eukaryotic cells, pyruvate enters the mitochondrial matrix. Each three-carbon pyruvate loses one carbon as carbon dioxide, is oxidized while NAD+ becomes NADH, and supplies a two-carbon acetyl group that joins coenzyme A. This oxidative decarboxylation is the link reaction.\n\nFor the two pyruvate produced from one glucose, the link reaction produces two acetyl-CoA, two carbon dioxide and two NADH. It does not directly produce ATP. Coenzyme A temporarily carries an acetyl group; its whole molecule is not consumed as a two-carbon respiratory substrate. Acetyl-CoA feeds the acetyl group into the Krebs cycle.',
        'Do not count link-reaction carbon dioxide as a product of glycolysis.', True),
    section('C1.2', 'krebs', 'Carbon and carriers in the Krebs cycle', [12],
        'In the mitochondrial matrix, a two-carbon acetyl group combines with four-carbon oxaloacetate to form six-carbon citrate. Reactions involving oxidation and two decarboxylations regenerate the four-carbon acceptor, enabling another turn.\n\nOne turn per acetyl group releases two carbon dioxide and forms three NADH, one reduced FAD (FADH2), and one ATP equivalent by substrate-level phosphorylation. Reduced FAD accounts for a fourth oxidation, alongside the three that reduce NAD+. One glucose supplies two acetyl groups, so these quantities double per glucose. Most of the energy transferred at this stage is in reduced carriers rather than directly formed ATP.\n\nThe cycle regenerates oxaloacetate; it does not double the starting acceptor on each turn. Oxygen is not directly consumed in the cycle, but continued operation depends on reoxidation of its reduced carriers.',
        'Two carbon atoms enter and two leave per turn, but they need not be the very same atoms in the first turn.', True),
    section('C1.2', 'electron-transport', 'Electron flow and the proton gradient', [13, 14, 16],
        'NADH donates electrons to carriers in the inner mitochondrial membrane and is oxidized to NAD+. Reduced FAD also supplies electrons. Successive electron transfers release energy that drives proton movement from the matrix into the intermembrane space. The membrane restricts free proton movement, allowing an electrochemical gradient to form.\n\nOxygen is the final electron acceptor. It combines with electrons and protons from the matrix to form water. Removing oxygen blocks sustained electron flow, inhibits regeneration of oxidized carriers and eventually slows the link reaction and Krebs cycle.\n\nElectron flow and proton flow are related but not identical: electrons pass between carriers, while protons are pumped across the membrane. Cristae provide a large area for these membrane proteins.',
        'Oxygen does not directly split glucose or carry protons through ATP synthase.', True),
    section('C1.2', 'chemiosmosis', 'Using a gradient to make ATP', [15],
        'Protons move down their electrochemical gradient from the intermembrane space to the matrix through ATP synthase. Their passage drives changes in the enzyme that couple ADP and inorganic phosphate to form ATP. This coupling of a proton gradient to ATP formation is chemiosmosis, part of oxidative phosphorylation.\n\nA proton leak can dissipate the gradient even while electrons continue along the transport chain. ATP production then falls because less proton flow is coupled through ATP synthase. By contrast, blocking ATP synthase initially steepens the gradient; as pumping against that gradient becomes difficult, electron transport and oxygen consumption can slow.\n\nAn intact inner membrane is therefore essential for efficient ATP synthesis. Electron transfer alone is insufficient if the energy cannot be retained in a usable gradient.',
        'A larger oxygen-consumption rate does not always imply a larger ATP-production rate, especially during uncoupling.', True),
    section('C1.2', 'fuels', 'Comparing respiratory substrates', [17],
        'Both carbohydrates and lipids can supply carbon for aerobic respiration. Fatty acids are broken into two-carbon acetyl groups carried by coenzyme A; they can then enter the Krebs cycle. Fatty-acid breakdown also supplies reduced carriers.\n\nLipids contain more carbon-hydrogen bonds and less oxygen relative to their mass than carbohydrates, so their complete oxidation generally releases more energy per gram. This makes fat an effective energy reserve. A per-gram comparison is not a per-molecule comparison: molecular masses differ.\n\nHuman anaerobic glycolytic ATP production depends on carbohydrate. Fatty acids cannot replace glucose to maintain that pathway when oxygen supply limits aerobic ATP production. Aerobic ATP yield also depends on coupling and transport, so a single rigid ATP total should not be assumed for all cells.',
        'A fuel with a higher energy yield per gram is not necessarily usable by every cell under every condition.', True),
]
r['questions'] = [
    old_r['m1'],
    question('w-atp-work', 'atp', 'written', 'explain',
        'Explain why a plant root cell may need ATP even though it is not photosynthesizing.',
        'ATP supports processes such as active transport of mineral ions or synthesis of cell components.~Respiration can regenerate ATP using carbon compounds supplied to the root.',
        'Plant cells require energy for cellular work, whether or not they capture light themselves.'),
    question('m-atp-cycle', 'atp-cycle', 'mcq', 'identify',
        'An active cell has a nearly constant ATP concentration. Which interpretation is supported?',
        'ATP use is approximately balanced by ATP regeneration.',
        'A steady pool can have rapid turnover; concentration alone does not measure the rate of use.',
        ['No ATP molecules are being hydrolysed.', 'ADP is not produced in the cell.', 'Every ATP-dependent reaction has stopped.']),
    question('w-hydrolysis', 'atp-cycle', 'written', 'explain',
        'Explain why ATP hydrolysis can power cellular work but ATP regeneration needs an energy input.',
        'ATP hydrolysis to ADP and phosphate is energetically favourable overall.~Enzymes couple that reaction to processes requiring energy.~The reverse conversion requires an energy input, supplied for example by respiration.',
        'Breaking a bond alone costs energy; explain the energetics of the overall coupled reaction.'),
    question('w-human-pathways', 'pathways', 'written', 'compare',
        'Compare aerobic respiration and anaerobic glucose metabolism in human cells, using oxygen, products, ATP yield and location.',
        'Aerobic respiration requires oxygen; the anaerobic route does not directly use it.~Complete aerobic oxidation produces carbon dioxide and water, whereas the human anaerobic route produces lactate.~Aerobic respiration yields substantially more ATP per glucose.~Glucose breakdown begins in the cytoplasm; aerobic stages also involve mitochondria, whereas the anaerobic lactate route is cytoplasmic.',
        'Make paired comparisons and distinguish respiration from breathing.'),
    question('m-red-cells', 'pathways', 'mcq', 'identify',
        'Mature human red blood cells have no mitochondria. Which statement correctly describes their ATP supply?',
        'They can produce ATP in the cytoplasm while forming lactate.',
        'Cytoplasmic glucose metabolism can supply ATP without mitochondrial aerobic stages.',
        ['They cannot make ATP at all.', 'They make most ATP by oxidizing fatty acids in mitochondria.', 'They release carbon dioxide when lactate forms.']),
    dict(old_r['d1'], sectionKey='respirometry'),
    question('d-respirometer-rate', 'respirometry', 'data', 'calculate',
        'In synthetic respirometer data, 2.0 g of seeds take up 0.60 cm³ of oxygen in 5.0 min after control correction. Calculate the mass-specific uptake rate and include units.',
        '0.60 / (5.0 × 2.0) = 0.060.~The rate is 0.060 cm³ g⁻¹ min⁻¹.',
        'Divide by both time and sample mass; do not multiply by the mass.'),
    question('d-respirometer-design', 'respirometry', 'data', 'evaluate',
        'A student compares oxygen uptake at 15 °C and 25 °C using one seed sample at each temperature, no carbon-dioxide absorbent and no equilibration period. Evaluate two weaknesses and propose improvements.',
        'Carbon-dioxide release can offset oxygen uptake; use a suitable absorbent separated from the tissue.~Temperature changes can alter gas volume without respiration; equilibrate and use a matched physical control.~One sample per treatment does not estimate biological variation; use independent replicates with matched seed mass and condition.',
        'Credit two explained weakness-improvement pairs. Repeating a reading from one sample is not equivalent to independent biological replication.'),
    question('m-nad-redox', 'redox', 'mcq', 'identify',
        'When NAD+ becomes NADH during substrate oxidation, what happens to NAD+?',
        'It gains electrons and is reduced.',
        'Oxidation and reduction are electron-transfer terms, not changes in the number of carrier molecules.',
        ['It loses electrons and is reduced.', 'It gains electrons and is oxidized.', 'It is converted directly into ATP.'], True),
    question('w-nad-recycling', 'redox', 'written', 'explain',
        'Explain why a cell needs to regenerate NAD+ rather than continually accumulating NADH.',
        'NAD+ accepts electrons during oxidation of respiratory substrates.~If it is not regenerated, the oxidized carrier becomes limiting and those reactions cannot continue at their previous rate.',
        'The cell recycles a finite carrier pool between oxidized and reduced forms.', hl=True),
    question('m-glycolysis-net', 'glycolysis', 'mcq', 'determine',
        'Two ATP are invested and four ATP are formed during glycolysis of one glucose. What is the net ATP gain?',
        'Two ATP', 'Net gain subtracts the initial ATP investment from the gross ATP output.',
        ['Four ATP', 'Six ATP', 'Zero ATP'], True),
    question('d-glycolysis-carbon', 'glycolysis', 'data', 'determine',
        'Three glucose molecules complete glycolysis. Determine the number of pyruvate, net ATP and NADH produced, and the number of carbon dioxide molecules released during this stage.',
        'Six pyruvate are produced.~Six ATP are gained net and six NADH are formed.~No carbon dioxide is released in glycolysis.',
        'Multiply each per-glucose yield by three. All 18 carbon atoms remain in six three-carbon pyruvate molecules.', hl=True),
    dict(old_r['w1'], sectionKey='fermentation', hlOnly=True),
    question('d-fermentation-block', 'fermentation', 'data', 'suggest',
        'A yeast culture without oxygen still has abundant glucose. A treatment prevents NADH oxidation in the ethanol pathway. Suggest why ATP production cannot be sustained at its previous rate.',
        'NAD+ regeneration is inhibited, so the available NAD+ pool falls.~Glycolysis requires NAD+ and therefore slows.~The loss of glycolytic ATP formation lowers the sustained ATP supply despite glucose remaining.',
        'The purpose of the fermentation step is carrier recycling; it does not itself add to the two ATP net glycolytic yield.', hl=True),
    question('m-link-carbon', 'link', 'mcq', 'identify',
        'Which description correctly follows carbon in one link reaction?',
        'Three-carbon pyruvate supplies a two-carbon acetyl group and one carbon dioxide.',
        'Decarboxylation removes one carbon from each pyruvate; NADH is formed but ATP is not made directly.',
        ['Six-carbon glucose directly produces two carbon dioxide and a four-carbon acceptor.', 'Three-carbon pyruvate becomes a three-carbon acetyl group without carbon loss.', 'Two-carbon acetyl-CoA gains carbon dioxide to form pyruvate.'], True),
    question('d-link-yield', 'link', 'data', 'calculate',
        'Four pyruvate molecules complete the link reaction. Calculate the acetyl-CoA, carbon dioxide, NADH and directly formed ATP produced.',
        'Four acetyl-CoA, four carbon dioxide and four NADH are formed.~No ATP is directly formed in the link reaction.',
        'Count per pyruvate, rather than per glucose: each pyruvate supplies one acetyl group.', hl=True),
    question('w-krebs-cycle', 'krebs', 'written', 'explain',
        'Explain why the Krebs pathway is a cycle rather than a one-way consumption of oxaloacetate.',
        'A four-carbon acceptor combines with a two-carbon acetyl group to make a six-carbon compound.~Oxidations and two decarboxylations return the pathway to a four-carbon acceptor.~Regeneration allows another acetyl group to enter.',
        'Track carbon counts and regeneration. Coenzyme A and oxaloacetate have different roles.', hl=True),
    question('d-krebs-yield', 'krebs', 'data', 'determine',
        'Two acetyl groups complete two turns of the Krebs cycle. Determine the total carbon dioxide, NADH, reduced FAD and ATP equivalents formed in those turns only.',
        'Four carbon dioxide and six NADH.~Two reduced FAD and two ATP equivalents.',
        'Do not add glycolytic or link-reaction yields when the question asks only about the cycle.', hl=True),
    question('m-mitochondrial-pumping', 'electron-transport', 'mcq', 'identify',
        'In respiring mitochondria, which process directly establishes the proton gradient across the inner membrane?',
        'Electron-transfer energy drives proton movement from the matrix into the intermembrane space.',
        'Protons are pumped against their electrochemical gradient; their later return through ATP synthase is a separate process.',
        ['ATP synthase moves electrons from oxygen into NADH.', 'Protons diffuse freely through the lipid membrane from matrix to intermembrane space.', 'Oxygen is pumped across the membrane in place of protons.'], True),
    question('w-oxygen-terminal', 'electron-transport', 'written', 'explain',
        'Explain why removal of oxygen eventually inhibits the Krebs cycle even though the cycle does not directly consume oxygen.',
        'Oxygen accepts electrons at the end of the electron-transport chain and participates in water formation.~Without this acceptor, sustained electron transfer and reoxidation of reduced carriers are inhibited.~Oxidized carriers become limiting for the link reaction and Krebs cycle.',
        'Connect the pathways through carrier recycling instead of placing oxygen directly into a Krebs-cycle reaction.', hl=True),
    question('m-proton-leak', 'chemiosmosis', 'mcq', 'identify',
        'A treatment increases proton leakage across the inner mitochondrial membrane without directly blocking electron carriers. Which outcome is most directly expected?',
        'Less ATP is made per unit of electron transfer because the gradient is dissipated.',
        'Leaking protons bypass ATP synthase, so respiratory electron flow can become less efficiently coupled to ATP formation.',
        ['More ATP is necessarily made because protons cross the membrane faster.', 'ATP synthase reverses the electrons carried by NADH.', 'The treatment necessarily increases net glycolytic ATP yield from two to four.'], True),
    question('d-coupling-data', 'chemiosmosis', 'data', 'suggest',
        'Synthetic mitochondrial data show oxygen use of 10 units and ATP output of 30 units before treatment. Afterwards oxygen use is 14 units and ATP output is 7 units. Suggest a mechanism consistent with the change.',
        'ATP produced per unit of oxygen use has fallen from 3.0 to 0.50.~Increased proton leakage or uncoupling could dissipate the gradient without stopping electron flow.~The data are consistent with uncoupling but do not identify a unique molecular cause.',
        'Use both measurements; increased oxygen use alone would give a misleading conclusion about ATP output.', hl=True),
    question('w-fuel-comparison', 'fuels', 'written', 'compare',
        'Compare carbohydrate and lipid as respiratory substrates in terms of energy per gram and use during human anaerobic ATP production.',
        'Complete lipid oxidation generally yields more energy per gram than carbohydrate because lipid is more reduced.~Human anaerobic glycolytic ATP production uses carbohydrate; fatty acids cannot substitute for glucose in that pathway.',
        'Higher energy density does not make fat an anaerobic fuel.', hl=True),
    question('d-fuel-units', 'fuels', 'data', 'calculate',
        'Use the synthetic rounded energy yields 17 kJ g⁻¹ for carbohydrate and 38 kJ g⁻¹ for lipid. Calculate the energy released by complete oxidation of 3.0 g of each. Explain why this does not by itself determine a cell’s ATP yield.',
        'Carbohydrate: 3.0 × 17 = 51 kJ.~Lipid: 3.0 × 38 = 114 kJ.~The fraction transferred to ATP depends on metabolic pathways and coupling; released energy also becomes heat.',
        'Energy per gram and ATP production are different quantities, so neither kJ total should be relabelled as a count of ATP molecules.', hl=True),
]
r['remaining'] = ('All 17 numbered understandings now have relevant teaching and linked practice, with core 1–6 and HL 7–17 separated. This is still partial revision support: add labelled mitochondrial/pathway diagrams, a wider range of unfamiliar respirometer traces and uncertainty analyses, practical execution and independent teacher review. References do not certify every assessment demand.')

p = by_code['C1.3']
old_p = {q['key']: q for q in p['questions']}
p['sections'] = [
    section('C1.3', 'transformation', 'Energy input and carbon products', [1, 2, 3],
        'Photosynthesis transfers light energy into chemical energy in organic compounds. Carbon dioxide supplies carbon; water supplies hydrogen in oxygenic photosynthesis. A simplified overall equation is 6 CO2 + 6 H2O → C6H12O6 + 6 O2, with light and photosynthetic pigments required. The detailed pathway builds smaller carbon compounds before sugars are assembled.\n\nPlants, algae and cyanobacteria perform oxygenic photosynthesis. Oxygen released as a by-product originates from water, not directly from carbon dioxide. Light supplies energy, not the carbon atoms in biomass.\n\nPlants also respire in light and darkness. Measured oxygen release can therefore represent net photosynthesis: gross photosynthetic oxygen production minus respiratory oxygen use.',
        'The simplified equation is not a claim that glucose is formed in one reaction.'),
    section('C1.3', 'chromatography', 'Separating photosynthetic pigments', [4],
        'In chromatography, dissolved pigments move with a solvent over a stationary material. Different pigments have different relative affinities for these phases and therefore travel different distances. Apply a small concentrated spot above the starting solvent level and mark the solvent front before it evaporates.\n\nRf = distance travelled by pigment from the origin / distance travelled by solvent front from the same origin. Measure to the centre of a pigment band. If a band travels 3.6 cm and the front 6.0 cm, Rf = 0.60, with no units.\n\nColour and Rf can support identification using standards run under the same conditions. Rf depends on the solvent and stationary phase, so a remembered value alone cannot establish identity across different methods.',
        'Measure from the origin, not the bottom of the paper, and do not treat Rf as a distance.'),
    section('C1.3', 'pigments', 'Absorption spectra and action spectra', [5, 6],
        'A pigment absorbs particular wavelengths of visible light; absorbed photons can raise electrons to higher energy states. Chlorophyll absorbs strongly in blue and red regions and less strongly in green, much of which is reflected or transmitted. Accessory pigments extend the wavelengths available.\n\nAn absorption spectrum plots how strongly a pigment or sample absorbs light against wavelength, usually in nanometres. An action spectrum plots photosynthetic activity, such as oxygen production, against wavelength. The vertical axes measure different things even when the overall patterns resemble each other.\n\nTo compare effects of wavelength, control the photon flux, temperature and carbon-dioxide availability. A whole-leaf action spectrum reflects multiple pigments and other biological factors, not only purified chlorophyll.',
        'Low absorption of green light does not mean every leaf has exactly zero photosynthesis in green light.'),
    section('C1.3', 'limiting', 'Interpreting limiting factors', [7],
        'Light intensity, carbon-dioxide availability and temperature can limit photosynthetic rate. Increasing one factor increases the rate only while that factor constrains the process. A plateau after increasing light may indicate that carbon dioxide or another condition is now limiting; the plateau alone does not identify which one.\n\nChange one factor at a time, control the others, allow equilibration and use independent replicates. A lamp can alter temperature as well as light intensity, so temperature must be measured and controlled.\n\nGas-exchange measurements need interpretation: oxygen-bubble counts are less precise than gas volume or concentration because bubble sizes vary. Net oxygen release combines photosynthetic production and respiratory use. An effect on net exchange does not automatically establish an identical effect on gross photosynthesis.',
        'A rising factor is not necessarily still limiting after the response has reached a plateau.'),
    section('C1.3', 'enrichment', 'Testing effects of elevated carbon dioxide', [8],
        'Growth chambers and greenhouses allow controlled changes in carbon dioxide while light, water and temperature are regulated. They help isolate causal effects, but enclosure conditions can differ from natural environments.\n\nFree-air carbon-dioxide enrichment (FACE) exposes plants to elevated carbon dioxide outdoors without enclosing them. It preserves more natural interactions with weather, soil and surrounding organisms, but controlling exposure and other conditions is harder. Replicated treatment and ambient-control plots improve interpretation.\n\nHigher carbon dioxide can increase photosynthesis when carbon availability limits it, but responses also depend on nutrients, water, temperature and acclimation. Results from one species and setting do not establish that all ecosystems will respond identically. Distinguish a short-term leaf rate from long-term biomass production.',
        'More realistic field conditions do not remove the need for controls and replication.'),
    section('C1.3', 'photosystems', 'Capturing light in photosystems', [9, 10],
        'Photosystems are pigment-protein complexes in thylakoid membranes. Antenna pigments absorb light and transfer excitation energy towards a reaction centre. A reaction-centre chlorophyll can then donate an excited electron to an acceptor, beginning directed electron transfer.\n\nMany antenna pigments can deliver energy to one reaction centre, increasing the probability of capturing usable light. Different accessory pigments absorb different wavelength ranges, broadening capture beyond that of a single chlorophyll molecule.\n\nEnergy transfer among antenna pigments is not the same as the electron-transfer sequence leaving the reaction centre. Photosystem II operates before photosystem I in the usual non-cyclic pathway, despite their numerical names.',
        'Antenna pigments collect excitation energy; they do not each generate a separate ATP molecule.', True),
    section('C1.3', 'photolysis', 'Replacing photosystem II electrons', [11],
        'Light excites electrons in photosystem II and electron transfer removes them from its reaction centre. Water is split at the photosystem-II-associated complex to replace those electrons. The products are electrons, protons and oxygen.\n\nThe balanced relationship is 2 H2O → O2 + 4 H+ + 4 electrons. Protons released on the thylakoid-lumen side contribute to the proton gradient, and oxygen can leave as a by-product. Sustained non-cyclic flow needs this electron supply.\n\nWater supplies the electrons; carbon dioxide has a different role in carbon fixation. Isotopic labelling of water can therefore trace the origin of the oxygen gas.',
        'Photolysis is associated with photosystem II, not the Calvin cycle or photosystem I.', True),
    section('C1.3', 'light-atp', 'Photophosphorylation and proton flow', [12],
        'Electrons leaving photosystem II pass through carriers towards photosystem I. Electron-transfer energy supports proton movement from the stroma into the thylakoid lumen. Water splitting also supplies lumen protons. The membrane limits proton leakage.\n\nProtons return down their electrochemical gradient through ATP synthase from the lumen to the stroma, driving ATP formation on the stromal side. This light-supported ATP formation is photophosphorylation.\n\nIn non-cyclic flow, water supplies electrons and the pathway ultimately produces reduced NADP as well as ATP, with oxygen released. In cyclic flow, electrons excited at photosystem I return through carriers. Cyclic flow can support additional ATP formation without net reduced NADP production or water splitting by that cycle.',
        'The lumen-to-stroma flow through ATP synthase is opposite to the energy-driven pumping direction.', True),
    section('C1.3', 'nadph', 'Photosystem I and reduced NADP', [13],
        'Light raises electrons in photosystem I to a higher energy state. In non-cyclic flow, electrons arrive to replace those lost by its reaction centre, while the excited electrons pass to acceptors that enable NADP+ reduction. NADP+ accepts two electrons and a proton from the stroma to form NADPH, also called reduced NADP.\n\nNADPH transfers reducing power to reactions in the stroma, including reduction of carbon compounds during the Calvin cycle. It is then oxidized to NADP+, which can accept electrons again. ATP and NADPH have different roles: ATP supplies energy through coupled reactions, whereas NADPH supplies reducing power.',
        'NADPH is not an alternative name for ATP, and reduced NADP is not the carrier used in glycolysis.', True),
    section('C1.3', 'spatial', 'Chloroplast compartments', [14],
        'The thylakoid membrane holds photosystems, electron carriers and ATP synthase in an organized arrangement. The thylakoid lumen is a small compartment in which proton concentration can increase. The stroma lies outside the thylakoids but inside the chloroplast envelope.\n\nLight-dependent reactions build the proton gradient across the thylakoid membrane, while ATP and NADPH become available on the stromal side. Enzymes for the Calvin cycle act in the stroma, where these products can be used. Thylakoid membranes provide a large working area and separate the two sides of the gradient.\n\nRupturing the membrane can eliminate efficient chemiosmotic ATP production even if some isolated pigments still absorb light.',
        'The stroma is not the fluid inside the thylakoid lumen.', True),
    section('C1.3', 'fixation', 'Rubisco and carbon entry', [15],
        'Carbon fixation incorporates inorganic carbon dioxide into an organic compound. In the stroma, the enzyme Rubisco catalyses addition of one carbon dioxide to five-carbon ribulose bisphosphate (RuBP). The unstable six-carbon product splits into two molecules of three-carbon glycerate 3-phosphate (GP).\n\nFor three carbon dioxide molecules, three RuBP molecules are used and six GP molecules result. The carbon count is 3 + 15 = 18, matching six three-carbon products. RuBP is the carbon-dioxide acceptor; Rubisco is the enzyme. Their similar names do not indicate identical roles.\n\nFixation alone is not completion of sugar synthesis: the products still need reduction and the acceptor must be regenerated.',
        'Carbon dioxide does not combine directly with ATP to become glucose.', True),
    section('C1.3', 'reduction', 'Producing triose phosphate', [16],
        'Glycerate 3-phosphate is converted to triose phosphate (TP) using ATP and reduced NADP. ATP supports the energetically demanding conversion, and NADPH supplies reducing power. ADP and NADP+ return to the pool available to the light-dependent reactions.\n\nFor fixation of three carbon dioxide molecules, conversion of the six GP molecules uses six ATP and six NADPH to form six TP molecules. Each TP contains three carbons. Most TP stays in the cycle to regenerate the carbon acceptor; only a fraction represents net carbon gain available for other synthesis.\n\nThe term light-independent does not mean these reactions usually run indefinitely in darkness: their supplies of ATP and NADPH depend on the light-dependent reactions.',
        'GP and TP both contain three carbons, but they differ in chemical state and cannot be treated as the same compound.', True),
    section('C1.3', 'regeneration', 'Recycling RuBP and counting net gain', [17],
        'For every three carbon dioxide fixed, six three-carbon TP molecules form. Five TP, containing fifteen carbons in total, regenerate three five-carbon RuBP molecules. Regeneration uses a further three ATP. The remaining one TP, containing three carbons, is the net product available to leave this cycle accounting.\n\nCombining reduction and regeneration gives nine ATP and six NADPH used per net TP from three carbon dioxide. Producing the carbon equivalent of a six-carbon sugar requires two net TP, so the totals double.\n\nFive-sixths of the TP produced is therefore recycled in this accounting. Removing all six TP as products would exhaust RuBP and prevent continued fixation.',
        'Count the net exported TP, not every TP molecule temporarily formed during the cycle.', True),
    section('C1.3', 'products', 'From fixed carbon to biomass', [18],
        'Products of the Calvin cycle provide carbon skeletons for the synthesis of other organic compounds. Triose phosphate can contribute to hexose formation; those sugars can be used to make sucrose for transport, starch for storage and cellulose for cell walls. Carbon skeletons also contribute to lipid and amino-acid synthesis.\n\nPhotosynthesis alone does not supply every element in biomass. Amino acids and proteins require nitrogen, obtained for example through assimilation of absorbed nitrate or ammonium. Other compounds require mineral nutrients such as phosphorus or sulfur.\n\nA plant can therefore be limited in growth by mineral supply even when light and carbon dioxide permit carbon fixation. Net biomass increase also depends on respiration and allocation of products.',
        'Carbon dioxide and water cannot by themselves supply the nitrogen atoms in proteins.', True),
    section('C1.3', 'interdependence', 'Why the reaction groups depend on each other', [19],
        'Light-dependent reactions supply ATP and NADPH to the Calvin cycle. In using them, the cycle regenerates ADP, phosphate and NADP+, which can support continued light-dependent reactions. The pathways exchange carriers as well as carbon and energy.\n\nWhen light is removed, new production of ATP and NADPH falls, so sustained Calvin-cycle activity becomes limited as available supplies are used. When carbon-dioxide supply is severely restricted, carbon fixation and consumption of ATP and NADPH can fall. Slower regeneration of NADP+ and ADP can then limit sustained electron flow and ATP formation.\n\nThese are linked responses, not claims that every intermediate becomes zero instantly. Storage pools and alternative electron pathways can affect the short-term response.',
        'Light-independent reactions are not independent of the products of light-dependent reactions.', True),
]
p['questions'] = [
    dict(old_p['m1'], distractors=['Carbon dioxide being fixed', 'Glucose transported into the leaf', 'The mineral ions absorbed by roots']),
    question('d-net-photosynthesis', 'transformation', 'data', 'calculate',
        'A leaf has gross photosynthetic oxygen production of 12 units per minute and respiratory oxygen use of 3 units per minute. Calculate net oxygen release.',
        '12 − 3 = 9 units per minute.', 'Net release subtracts simultaneous respiratory use from gross production.'),
    question('d-rf', 'chromatography', 'data', 'calculate',
        'A pigment band travels 42 mm and the solvent front travels 60 mm from the same origin. Calculate Rf and state whether it has units.',
        'Rf = 42 / 60 = 0.70.~Rf is dimensionless.',
        'The ratio is unchanged if both distances are converted to centimetres.'),
    question('w-rf-identification', 'chromatography', 'written', 'evaluate',
        'A student identifies a pigment solely because its Rf matches a value from a different solvent system. Evaluate that identification.',
        'Rf depends on the solvent and stationary phase, so values from different systems are not directly decisive.~Compare colour and a known standard run under the same conditions before assigning identity.',
        'Chromatographic movement is evidence for identification, not an environment-independent molecular label.'),
    dict(old_p['w1'], sectionKey='pigments'),
    question('d-spectra', 'pigments', 'data', 'suggest',
        'Under matched photon flux, synthetic leaf data show photosynthetic rates of 8, 3 and 7 units at 450, 550 and 660 nm respectively. Suggest why the pattern resembles, but need not exactly match, the absorption spectrum of purified chlorophyll.',
        'Blue and red wavelengths are strongly absorbed by chlorophyll, supporting higher rates than green in these data.~An intact leaf contains accessory pigments and other biological factors absent from a purified chlorophyll sample.',
        'Do not conclude that all green light is unusable or that the vertical axes of both spectra measure absorption.'),
    old_p['d1'],
    question('d-lamp-confound', 'limiting', 'data', 'explain',
        'Moving a lamp closer to pondweed increases bubble count and water temperature. Explain why this does not isolate the effect of light intensity, and suggest two improvements.',
        'Both light intensity and temperature changed, so the result cannot be attributed to light alone.~Control and monitor water temperature while changing measured light intensity.~Measure oxygen volume or concentration rather than assuming every bubble has equal volume; use independent replicates.',
        'Identify the confounding variable and connect each improvement to the weakness it addresses.'),
    question('w-face-comparison', 'enrichment', 'written', 'compare',
        'Compare a controlled growth chamber and a FACE field experiment for studying elevated carbon dioxide.',
        'A chamber makes it easier to hold other conditions constant, helping isolate effects of carbon dioxide.~FACE retains more natural environmental interactions without enclosing the plants.~Field conditions are harder to control, so replicated treatment and control plots are important.',
        'Neither method is universally superior; their control and ecological realism differ.'),
    question('d-co2-generalization', 'enrichment', 'data', 'evaluate',
        'In synthetic field data, added carbon dioxide increases biomass by 18% in watered, fertilized plots but by 2% in dry, nutrient-poor plots. Evaluate the claim that elevated carbon dioxide will increase all plant growth by 18%.',
        'The response depends on water and nutrient conditions, so the 18% result cannot be applied to every setting.~Other species, climates and exposure durations may respond differently.~Replication and variation are needed to judge how reliably the measured treatment differences are estimated.',
        'Separate the observed response in particular plots from a universal prediction.'),
    question('m-antenna', 'photosystems', 'mcq', 'identify',
        'What is an advantage of grouping antenna pigments around a reaction centre?',
        'Multiple pigments can capture light and transfer excitation energy towards the reaction centre.',
        'Antenna organization increases light capture without requiring every pigment to function as an independent reaction centre.',
        ['Each antenna pigment independently fixes carbon dioxide.', 'It removes the need to replace reaction-centre electrons.', 'It makes all visible wavelengths equally absorbed.'], True),
    question('w-photosystem-transfer', 'photosystems', 'written', 'distinguish',
        'Distinguish excitation-energy transfer among antenna pigments from electron transfer out of a reaction centre.',
        'Antenna pigments pass excitation energy towards a reaction centre.~An excited reaction-centre electron is transferred to an electron acceptor, beginning directed electron flow.',
        'The collected energy and the electron leaving the reaction centre are related but should not be described as the same moving object.', hl=True),
    question('d-water-splitting', 'photolysis', 'data', 'determine',
        'Using 2 H2O → O2 + 4 H+ + 4 electrons, determine the oxygen, protons and electrons supplied by splitting six water molecules.',
        'Three oxygen molecules, twelve protons and twelve electrons.',
        'Multiply every term in the balanced relationship by three.', hl=True),
    question('m-psii-water', 'photolysis', 'mcq', 'identify',
        'Which role of water is directly linked to sustained photosystem II activity?',
        'Water supplies replacement electrons and contributes protons and oxygen through splitting.',
        'The reaction centre needs replacement electrons after photoexcited electrons are transferred away.',
        ['Water supplies the carbon fixed into GP.', 'Water converts Rubisco into RuBP.', 'Water accepts electrons at the end of the mitochondrial electron chain.'], True),
    question('m-chloroplast-protons', 'light-atp', 'mcq', 'identify',
        'In a functioning chloroplast, which proton movement is coupled to ATP formation by ATP synthase?',
        'From the thylakoid lumen to the stroma',
        'ATP synthase uses the downhill return flow rather than the pumping step that builds the gradient.',
        ['From the stroma into the thylakoid lumen', 'From the mitochondrial matrix into the stroma', 'From the cytoplasm directly into RuBP'], True),
    question('w-cyclic-flow', 'light-atp', 'written', 'compare',
        'Compare cyclic and non-cyclic electron flow with respect to ATP, reduced NADP and oxygen production.',
        'Both can support ATP formation through a proton gradient.~Non-cyclic flow supplies electrons to reduce NADP and involves water splitting with oxygen release.~Cyclic flow returns photosystem-I electrons through carriers and does not itself produce net reduced NADP or oxygen.',
        'Cyclic flow can supplement ATP supply without equivalent extra NADPH production.', hl=True),
    question('m-nadph-role', 'nadph', 'mcq', 'identify',
        'Which statement distinguishes the roles of ATP and NADPH in carbon reduction?',
        'ATP supports energy-requiring reactions, while NADPH supplies reducing power.',
        'Both are needed, but they perform different chemical roles.',
        ['NADPH supplies the carbon atoms, while ATP supplies nitrogen.', 'ATP supplies electrons to photosystem I, while NADPH is the enzyme Rubisco.', 'ATP and NADPH are interchangeable names for the same molecule.'], True),
    question('w-nadp-reduction', 'nadph', 'written', 'outline',
        'Outline how NADP+ becomes reduced NADP during non-cyclic electron flow.',
        'Light excites electrons in photosystem I and they pass to acceptors.~NADP+ accepts two electrons and a proton from the stroma to form NADPH.',
        'Reduced NADP is a reusable carrier, not a carbon product of the Calvin cycle.', hl=True),
    question('w-chloroplast-layout', 'spatial', 'written', 'explain',
        'Explain how thylakoid compartmentalization supports photosynthetic ATP production and its use.',
        'The membrane separates lumen and stroma and restricts proton leakage so an electrochemical gradient can form.~ATP synthase couples proton return to ATP formation on the stromal side.~ATP can then be used by Calvin-cycle enzymes in the stroma.',
        'Connect structure to function rather than only naming chloroplast parts.', hl=True),
    question('d-broken-thylakoids', 'spatial', 'data', 'suggest',
        'An isolated preparation still absorbs light after its thylakoid membranes are ruptured, but makes very little ATP. Suggest why light absorption is not enough.',
        'Ruptured membranes cannot maintain an effective proton gradient between lumen and stroma.~Without the gradient, ATP synthase lacks the coupled driving force for efficient ATP formation.',
        'Pigment absorption and energy coupling are distinct requirements.', hl=True),
    question('m-rubisco-rubp', 'fixation', 'mcq', 'identify',
        'Which statement assigns Rubisco and RuBP their correct roles?',
        'Rubisco is an enzyme; RuBP is a five-carbon carbon-dioxide acceptor.',
        'The enzyme catalyses fixation, while the acceptor contributes carbon to the unstable product.',
        ['RuBP is an enzyme; Rubisco is a five-carbon sugar.', 'Both are names for the same protein.', 'Rubisco is ATP; RuBP is reduced NADP.'], True),
    question('d-fixation-carbon', 'fixation', 'data', 'determine',
        'Three CO2 molecules are fixed using three RuBP molecules. Determine the number of GP molecules formed and check the carbon balance.',
        'Six GP molecules form.~Three carbons from CO2 plus fifteen carbons from RuBP equal eighteen carbons, matching six three-carbon GP molecules.',
        'The fixed carbon is added to pre-existing acceptor carbon, so GP output exceeds the number of newly fixed carbon atoms.', hl=True),
    question('w-gp-reduction', 'reduction', 'written', 'explain',
        'Explain why conversion of GP to TP depends on both ATP and reduced NADP.',
        'ATP supplies energy through coupled reactions needed for the conversion.~Reduced NADP supplies reducing power and becomes NADP+.~Without these inputs, GP cannot be continuously converted to TP at the previous rate.',
        'Name both roles; saying only that both supply energy misses the electron-transfer role of NADPH.', hl=True),
    question('d-reduction-demand', 'reduction', 'data', 'calculate',
        'For three CO2 fixed, six GP are reduced using six ATP and six NADPH. Calculate the ATP and NADPH used in this reduction stage for six CO2 fixed. Do not include RuBP regeneration.',
        'Twelve ATP and twelve NADPH.',
        'This is the reduction stage only. Counting regeneration would add further ATP.', hl=True),
    question('d-calvin-accounting', 'regeneration', 'data', 'calculate',
        'Calculate the CO2, ATP and NADPH requirements for two net TP molecules, using three CO2, nine ATP and six NADPH per net TP.',
        'Six CO2, eighteen ATP and twelve NADPH.',
        'Two net three-carbon TP supply the carbon equivalent of one six-carbon sugar, not twelve net TP.' , hl=True),
    question('w-tp-recycling', 'regeneration', 'written', 'explain',
        'Explain why only one of six TP molecules formed per three CO2 fixed is a net product in the Calvin-cycle accounting.',
        'Five three-carbon TP supply fifteen carbons to regenerate three five-carbon RuBP molecules.~Only the remaining TP is available as net exported carbon.~Exporting all six would deplete the carbon-dioxide acceptor and prevent continued fixation.',
        'Show conservation of carbon and the need to regenerate the acceptor.', hl=True),
    question('w-protein-nitrogen', 'products', 'written', 'explain',
        'Explain why a plant with adequate light and carbon dioxide may still require nitrate or ammonium to increase protein production.',
        'Fixed carbon supplies carbon skeletons but proteins also contain nitrogen.~Absorbed inorganic nitrogen can be assimilated into amino acids, which form proteins.',
        'Carbon fixation does not supply elements absent from carbon dioxide and water.', hl=True),
    question('m-carbon-allocation', 'products', 'mcq', 'identify',
        'Which set consists of products that can use carbon ultimately derived from Calvin-cycle intermediates?',
        'Sucrose, starch, cellulose and amino-acid carbon skeletons',
        'Fixed carbon supports several synthetic pathways; amino-acid synthesis additionally requires a nitrogen source.',
        ['Only glucose, because no other compound can use fixed carbon', 'Only oxygen and mineral nitrate', 'Rubisco but no carbohydrates'], True),
    question('w-dark-response', 'interdependence', 'written', 'explain',
        'Explain why Calvin-cycle activity cannot be sustained indefinitely after illumination stops, even though light is not directly absorbed in those reactions.',
        'New supplies of ATP and NADPH from the light-dependent reactions decline.~The available pools are consumed, limiting reduction of GP and regeneration of RuBP.~An immediate total stop is not implied because pools and transient responses exist.',
        'Distinguish no direct light-absorption step from no dependence on light-supported products.', hl=True),
    question('d-co2-feedback', 'interdependence', 'data', 'suggest',
        'In a synthetic experiment, severe carbon-dioxide restriction under constant light is followed by NADPH accumulation and declining sustained oxygen evolution. Suggest a link between the observations.',
        'Reduced carbon fixation lowers consumption of NADPH and regeneration of NADP+.~Availability of the terminal electron acceptor NADP+ can then limit sustained non-cyclic electron flow.~This can lower water splitting and oxygen production; the data do not exclude alternative pathways or other limitations.',
        'Connect the two reaction groups through carrier recycling, without claiming that all short-term responses must be identical.', hl=True),
]
p['remaining'] = ('All 19 numbered understandings now have relevant teaching and linked practice, with core 1–8 and HL 9–19 separated. This remains partial revision support: add labelled chloroplast/photosystem diagrams, real pigment and action-spectrum images, further unfamiliar datasets and uncertainty analysis, practical execution and independent teacher review. References do not certify every assessment demand.')

# Verify every section has a question and every original question ID survives.
for topic, original in [(r, old_r), (p, old_p)]:
    assert set(original) <= {q['key'] for q in topic['questions']}
    for s in topic['sections']:
        linked = [q for q in topic['questions'] if q['sectionKey'] == s['key']]
        assert linked and all(bool(q.get('hlOnly')) == bool(s['hlOnly']) for q in linked)
path.write_text(json.dumps(topics, ensure_ascii=False, indent=2) + '\n')

# The independent test oracle gains only boundaries checked in the guide.
audit = Path('scripts/audit_biology.py')
text = audit.read_text()
old = "    'C2.2': (7, 16), 'C4.2': (22, 22), 'D1.3': (7, 10),"
new = "    'C1.2': (6, 17), 'C1.3': (8, 19),\n" + old
assert old in text and "'C1.2': (6, 17)" not in text
audit.write_text(text.replace(old, new))
